In [1]:
import torch
print(torch.__version__)

2.10.0+cu128


In [2]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU is available!
Using GPU: Tesla T4


In [4]:
a=torch.empty(2,3)

In [8]:
b=torch.zeros(2,3)
c=torch.ones(2,3)
print(b)
print(c)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [14]:
torch.manual_seed(100)
torch.rand(2,3)


tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [16]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [21]:
print(torch.arange(0,10,2))
print(torch.arange(0,11))
print(torch.eye(5))

tensor([0, 2, 4, 6, 8])
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


**Operation**

In [24]:
torch.manual_seed(100)
x=torch.rand(2,3)
y=torch.rand(2,3)
print(x)
print(y)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])
tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])


In [27]:
y-x
x/0.12
y/0.2

tensor([[1.3135, 0.2142, 1.0401],
        [0.5902, 0.6085, 3.6780]])